# create new user with api
# POST http://localhost:5000/v1/user
# Content-Type: application/json

# {
#     "name":"abhi",
#     "company":"react js crm",
#     "address":"mumbai",
#     "phone":"8655666021",
#     "email":"abhim@gmail.com",
#     "password":"12345678"
# }

# # # user login api
# POST http://localhost:5000/v1/user/login
# Content-Type: application/json

# {
#     "email":"abhi@gmail.com",
#     "password":"newpassword"
# }

# # Get user profile endpoint
# GET http://localhost:5000/v1/user
# Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiaGltQGdtYWlsLmNvbSIsImlhdCI6MTY0MjkwNDA4MywiZXhwIjoxNjQyOTA0OTgzfQ.9UL0tx9YFuoYhwhgAWqAMdH1xKo2dn3_31zRhOyy2qc


# # # Get new token
# GET http://localhost:5000/v1/tokens
# Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiaGltQGdtYWlsLmNvbSIsImlhdCI6MTY0MjkwMzIyOCwiZXhwIjoxNjQyOTA0MTI4fQ.HPcDwLkPRq1d3Gyq7MGH1cK2KDL_ftx6h3N6lzXTE6s


# # # password reset pin Endpoint
# POST http://localhost:5000/v1/user/reset-password
# Content-Type: application/json

# {
#     "email":"abhi@gmail.com"
# }


# # Update reset password end point
# PATCH  http://localhost:5000/v1/user/reset-password
# Content-Type: application/json

# {
#     "email":"abhi@gmail.com",
#     "pin" :052985,
#     "password":"updatedpassword"
# }

# user logout endpoint

# DELETE  http://localhost:5000/v1/user/logout
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiaGltQGdtYWlsLmNvbSIsImlhdCI6MTY0NDU4Njk3OCwiZXhwIjoxNjQ0NTg3ODc4fQ.bnCCv_-PWAJNP7zir8fLo0vXJ76fMHTAeUiaP9nYzbg